### ISSUE TITLE
Snippet without children matches code with children

### ISSUE THREAD

**Issue by seren5240** [getgrit/gritql#102]
NB please do not edit the editor from this link. Copy a forked version to experiment.

https://app.grit.io/studio?key=hWu-nA-6hu6_esJtvoXag

**Comment by ilevyor** [comment]
This is the default behavior for a snippet. I recently added a way to specify that a node with no children in a snippet must only match other nodes with no children. we could invert this, but it could break backwards compatibility for a patterns (would have to try and see).

**Comment by morgante** [comment]
I think we should try inverting it and see if the stdlib breaks.
