### ISSUE TITLE
Python: blank lines break function rewrite

### ISSUE THREAD

**Issue by 5tefan** [getgrit/gritql#109]
## Summary

Blank lines break function rewrite.

## Repro

With gritql query:

```
engine marzano(0.1)
language python

pattern resolver_func($name, $parameters, $return_type, $body) {
    function_definition($name, $parameters, $return_type, $body) as $function where {
        $name <: "resolve",
        $return_type <: "Out1 | None"
    }
}

pattern change_signature() {
    resolver_func($return_type, $body, $name, $parameters) => 
    `
def $name($parameters) -> Out2 | None:
    # TODO: fix body
    $body
    `
}

change_signature()
```

And test Python code:

```python
from dataclasses import dataclass


@dataclass(frozen=True)
class Out1:
    res: str


@dataclass(frozen=True)
class Out2:
    res: str


@dataclass(frozen=True)
class A:
    a: str

    def resolve(self, a: str, b: str) -> Out1 | None:
        1 + 1
        print("hi")

        1 + 1

        return Out1("hi")


@dataclass(frozen=True)
class B:
    a: str

    def resolve(self, a: str, b: str) -> Out1 | None:
        return Out1("hi")

```

I get the following error message:

> Error expected line to start with 8 spaces, code is either not indented with spaces, or does not consistently indent code blocks

Rewriting `A` as:

```python
@dataclass(frozen=True)
class A:
    a: str

    def resolve(self, a: str, b: str) -> Out1 | None:
        1 + 1
        print("hi")
        1 + 1
        return Out1("hi")
```

Then it works as expected.

Seems to be coming from here ish: https://github.com/getgrit/gritql/blob/542cca3c316b476818ebdd37f71833d096eeb365/crates/core/src/binding.rs#L157-L163

**Comment by morgante** [comment]
Possibly related to https://github.com/getgrit/gritql/pull/99 and might be fixed in the next release.

**Comment by morgante** [comment]
Seems to be working with the latest release: https://app.grit.io/studio?key=-BIweuCKk3wzbwsX85F6-

@5tefan Can you confirm?

**Comment by 5tefan** [comment]
Awesome -- looks fixed to me!! Love seeing a test case in there.
