### ISSUE TITLE
Python: Invalid rewrite for `$something => .`

### ISSUE THREAD

**Issue by 5tefan** [getgrit/gritql#121]
## Summary

Invalid rewrites when trying to remove a node.

## Repro

https://app.grit.io/studio?key=Mtz14P9InB2-2vdJYtxLk

```gritql
engine marzano(0.1)
language python


pattern test_func($name, $parameters, $return_type, $body) {
    function_definition($name, $parameters, $return_type, $body) as $function where {
        $name <: r"test_.*",
    }
}

pattern test_class($name, $superclasses, $body) {
    class_definition($name, $superclasses, $body) as $cls where {
        $superclasses <: contains `TestCase`,
    }
}

test_func($return_type) as $function where {
    $function <: within test_class(),
    $return_type => .
}
```

And target:

```python
from unittest import TestCase

class TestFirst(TestCase):
  def test_typed(self) -> None:
    pass

  def test_another(self):
    pass
```

Produces the following:

<img width="813" alt="image" src="https://github.com/getgrit/gritql/assets/5855806/4397b22d-f2e4-412f-9c06-b41dddbac4a7">

The dangling ` -> :` is invalid, the `->` should be removed as well.

I also noticed this in some cases while removing some kwarg from a list of kwargs -- unfortunately I don't have a repro on that though. Removing a kwarg in some cases left a dangling comma, i.e. `Something(a=1, b=2, c=3)` -> "remove kwarg `a`" -> `Something(, b=2, c=3)` invalid.

**Comment by morgante** [comment]
This would fall under the category of removing "orphaned" nodes. Ex. in TypeScript we will remove trailing semicolons if a statement is deleted.

The relevant code is here: https://github.com/getgrit/gritql/blob/0ca9be8758f7181caff713926385758a2a109e46/crates/language/src/xscript_util.rs#L70C15-L70C36

We'd welcome a contribution to extend this to Python.

As a workaround, you can rewrite the whole node.

```
engine marzano(0.1)
language python


pattern test_func($name, $parameters, $return_type, $body) {
    function_definition($name, $parameters, $return_type, $body) as $function where {
        $name <: r"test_.*",
    }
}

pattern test_class($name, $superclasses, $body) {
    class_definition($name, $superclasses, $body) as $cls where {
        $superclasses <: contains `TestCase`,
    }
}

test_func($parameters, $body, $name) as $function where {
    $function <: within test_class(),
    $function => `def $name($parameters): $body`
}
```

**Comment by 5tefan** [comment]
Thanks for the code pointer! I may check it out, but can't promise I have time immediately.

Regarding your suggestion, unfortunately I have noticed that rewriting the whole node drops comment nodes at the start of `$body`.

https://app.grit.io/studio?key=CMQmy5VOetz2Rc5F1Fq-L

<img width="1006" alt="image" src="https://github.com/getgrit/gritql/assets/5855806/10bc5106-06b3-412a-bcfe-0bccb26c4d7d">

**Comment by morgante** [comment]
Yeah, it looks like that's a problem with the grammar including the comment inside the parent instead of the body.

**Comment by morgante** [comment]
The orphan issue was straightforward to fix, thanks for the minimal test case: https://github.com/getgrit/gritql/pull/122
