### ISSUE TITLE
Allow patterns test to filter out patterns which use ai.

### ISSUE THREAD

**Issue by ilevyor** [getgrit/gritql#126]
The standard library has patterns that use ai, but ai functionality is not open source, so running `grit patterns test` using an open source build fails to run, as the patterns which make use of ai fail to compile. easiest fix (although a bit hacky) would be to filter out tests that don't compile, and list them as skipped due to compilation failures at the end of the report.

**Comment by morgante** [comment]
We already have this. Just use --exclude.
