### ISSUE TITLE
The `sequential` example in the docs doesn't work

### ISSUE THREAD

**Issue by jonathan-s** [getgrit/gritql#156]
When you try the following pattern described in the [docs for sequential](https://docs.grit.io/language/patterns#sequential) it doesn't work in the studio. 

You also get the following warning. 

```
Log Warning: sequential matches at the top of the file. If a pattern matched outside of a 
sequential, but no longer matches, it is likely because naked patterns are 
automatically wrapped with `contains bubble <pattern>`
```

This warning is somewhat unclear, as it doesn't really tell the user how they should proceed to make things work the way they expect it to.

**Comment by ilevyor** [comment]
good catch in the docs.

The error message is trying to explain that most patterns are auto wrapped 

https://docs.grit.io/language/bubble#pattern-auto-wrap

sequential is not auto wrapped because it only matches on files, so the pattern inside of a sequential needs to match a top level file. in this case the easy fix is to insert a contains in front of each step like so:

```
sequential {    
    contains `console.log($message)` => `console.warn($message)`,
    contains `console.warn($message)` => `console.info($message)`
}
```

**Comment by morgante** [comment]
> Are there other strategies besides using `contains`?

The core thing is that each step is matching the *file* as a whole. In most cases, you want to look for some code inside the file so `contains` is the best option. Why do you want an alternative?

**Comment by morgante** [comment]
The bubble needs to go around the scope you actually want to isolate, like this:

```
sequential {
    file($body) where $body <: contains bubble `def $name($args, $...): $funcbody` where {
        $args <: `self` => .
    }
}
```

**Comment by jonathan-s** [comment]
@morgante Thank you. 
Worth noting that the example in documentation here > https://docs.grit.io/language/patterns#sequential

contains

```
sequential {
    bubble file($body) where $body <: contains `console.log($message)` => `console.warn($message)`,
    bubble file($body) where $body <: contains `console.warn($message)` => `console.info($message)`
}
```

In other words it is using bubble the very first. 

Also I'm noticing that `or` does not seem to work together with bubble. Is there a way to make that work? 

Ie the following code does not work as expected finding zero matches. Though each sequence in separation does work as expected. 

```
sequential {
    file($body) where $body <: contains bubble `class $name($parent): $funcbody` => $funcbody,
    file($body) where $body <: contains bubble or {
        `self.assertEqual($first, $second)` => `assert $first == $second`,
        `self.assertEqual($first, $second, $third)` => `assert $first == $second`
    },
}
```
