### ISSUE TITLE
Yaml auto-indentation does not behave as expected

### ISSUE THREAD

**Issue by morgante** [getgrit/gritql#189]
If you include indentation in the output of a yaml pattern, it isn't always distributed properly. See [this case](https://github.com/getgrit/gritql/pull/188/files#diff-041f066ed81994bf9c7f0a0f795e5c85faab0c47d152231fce8b15d7bd2aa45aR12040) for example.

**Comment by ilevyor** [comment]
Should be fixed by: https://github.com/getgrit/gritql/pull/192
