### ISSUE TITLE
java cast not working

### ISSUE THREAD

**Issue by urbit-pilled** [getgrit/gritql#193]
https://app.grit.io/studio?key=YVJiMMWALUv96M2urFuXf

this pattern doesn't work: `($x) a;` => `(long) a;`
but this does: `($x) a` => `(long) a`

I think it has to do with this
https://github.com/getgrit/gritql/blob/ac64fd1bb71013634612f72e8889c934ce8d712c/crates/language/src/language.rs#L425-L431

 `GRIT_VAR = (µx) a` is within range but `GRIT_VAR = (µx) a;` is out of range.

**Comment by morgante** [comment]
This is to be expected, since the `;` is not part of the cast, but instead is part of the outer statement.

**Comment by urbit-pilled** [comment]
I have updated the studio link with this:

```
class Bar {
    void main() {
        (string) a;
        long a = (string) a;
    }
}
```

`($x) a;` => `(long) a;` matches only the first cast. `(string) a;`
`($x) a` => `(long) a` matches both casts.  `(string) a;` and `long a = (string) a;`
Is this expected behavor?

**Comment by morgante** [comment]
Yes, that's expected:

- `($x) a;` corresponds to a statement consisting of only a cast
- `($x) a` corresponds to a cast, no matter where it is found.

**Comment by urbit-pilled** [comment]
ok, thanks for the clarification, I had this same issue with the php language, looks like it's working as expected.
