### ISSUE TITLE
Flow grammar

### ISSUE THREAD

**Issue by morgante** [getgrit/gritql#215]
We would like to support Flow as an alternative "flavor" for JavaScript/TypeScript as a language for matching against.

## Acceptance criteria
1. Working grammar + language support
2. At least 10 test cases, including rewrites and metavariables.

## Assignment approach
Since this is a large project, here is how we will tackle it:
- If anyone who has already successfully contributed a grammar wants to take it on, we will assign them first dibs.
- Others are welcome to contribute. We will assign the bounty to the first *major* PR submitted that is close to complete.

**Comment by ilevyor** [comment]
we already support flow, through the TSX grammar: https://github.com/tree-sitter/tree-sitter-typescript

**Comment by morgante** [comment]
We should add an alias I think.
