### ISSUE TITLE
`embeddings` dependency

### ISSUE THREAD

**Issue by arendjr** [getgrit/gritql#23]
I discovered a dependency on the `embeddings` crate, which seems to be an empty placeholder: https://github.com/getgrit/gritql/blob/main/crates/core/Cargo.toml#L17

Is this something that is still supposed to be initialized, or something that should be cleaned up?

**Comment by morgante** [comment]
It's a placeholder for some internal experiments we’re running for retrieving from an embedding database. We have a few similar crates, but they're all optional dependencies.
