### ISSUE TITLE
Python indentation issue - error

### ISSUE THREAD

**Issue by jonathan-s** [getgrit/gritql#250]
This is in fact valid python code. Though it throws an error when trying to do something with it. Check it here https://extendsclass.com/python-tester.html or in your local environment. 

```python
def test_yaml_file():
    """some test comment"""
    variable = """
en:
  formtastic:
    labels:
      title: "Title"  # Default global value
      article:
        body: "Article content"
      post:
        new:
          title: "Choose a title..."
          body: "Write something..."
        edit:
          title: "Edit title"
          body: "Edit body"
        """
```

Also worth noting that the indentation inside the comment IS important in this case, so it should not be re-formatted.

**Comment by ilevyor** [comment]
We assume that a binding corresponds to a scope, and therefore preserves indentation. multiline strings can violate this assumption, I'll add some special casing logic for this
