### ISSUE TITLE
Feature request: Specify range for query on a specific file

### ISSUE THREAD

**Issue by noahbald** [getgrit/gritql#264]
I'm working on [a Neovim plugin](https://github.com/noahbald/grit-telescope.nvim) where you can select results of a dry-run to apply to a project.

At the moment, if a user selects a result to be applied, it's only possible to run the apply command across the whole file which would update other results in the same file too.

My request is for us have an option to specify a range of lines/columns to apply onto. 

As an example
```sh
# Specify a range of lines
grit apply "`const` => `let`" my-file.js --range 12-13

# Specify a range of lines and columns
grit apply "`const` => `let`" my-file.js --range 12:7-13:6

# Specify a specific point
# Only 1 match will be applied to the first match after the specified point
grit apply "`const` => `let`" my-file.js --range 12:7
```

**Comment by morgante** [comment]
This should be doable already with the `--only-in-json` parameter: https://github.com/getgrit/gritql/blob/05803744ea1d73986512412d913f1dc2a97e0a13/crates/cli/src/commands/apply.rs#L21

**Comment by morgante** [comment]
It follows the same format as eslint's output. On a shell, you don't really need a file since you can pipe a file handler directly.

Here's an example:
```
grit apply --dry-run fix.grit --only-in-json <( echo '[{"filePath":"file.js", "messages": [{ "line": 4, "column": 1, "endLine": 4, "endColumn": 50}]}]' )
```

I don't think people are likely to directly generate this (it's useful for automation), so I'm inclined to stick to JSON.

**Comment by morgante** [comment]
I'm dropping the file requirement, so you can just do this:

```
grit apply --dry-run fix.grit --only-in-json '[{"filePath":"file.js", "messages": [{ "line": 4, "column": 1, "endLine": 4, "endColumn": 50}]}]'
```

**Comment by noahbald** [comment]
This requires me to know the precise endLine and endColumn, which the output of `apply` doesn't provide (unless we parse the output).

The third example I gave in my original comment is what I'd ideally like to be able to do

**Comment by morgante** [comment]
`end` is available on all ranges in the output when running with `--jsonl`. I'm not sure how you are even planning to get the *start* range without parsing the output. It's inevitable.

**Comment by noahbald** [comment]
@morgante I was depending on just the lines of the compact output. But using jsonl has been fairly straightforward to use in the end, so happy for this issue to be closed.
