### ISSUE TITLE
(Help) How Can I ensure import in js?

### ISSUE THREAD

**Issue by gaki2** [getgrit/gritql#272]
I want to make a condition saying that 
if `CommonButton` is imported from '@miri-unicorn/miricanvas-ds', then ~~~~.

```grit
engine marzano(0.1)
language js

`CommonButton` as $common_button where {
    and {
        $base = `@miri-unicorn/miricanvas-ds`,
        // this is not working.
        $common_button <: imported_from($base),
        // Below code is not working even though I imported { CommonButton } from '@miri-unicorn/miricanvas-ds'.
        $common_button <: remove_import($base),
        $button = `Button`,
        $source = `@miri-unicorn/miricanvas-ds/v2`,
        $button <: ensure_import_from($source),
    }
}
```

Is there any pattern i can use? 
`imported_from` pattern seems to be not working.

<img width="1675" alt="스크린샷 2024-04-24 오전 11 19 07" src="https://github.com/getgrit/gritql/assets/76833478/3fb06db0-b491-473a-bfa8-43921d9cb327">

**Comment by morgante** [comment]
You need to include the quotes:

```
engine marzano(0.1)
language js

`CommonButton` as $common_button where {
        $base = `'@miri-unicorn/miricanvas-ds'`,
        // this is not working.
        $common_button <: imported_from($base),
        // // Below code is not working even though I imported { CommonButton } from '@miri-unicorn/miricanvas-ds'.
        $common_button <: remove_import($base),
        $button = `Button`,
        $source = `@miri-unicorn/miricanvas-ds/v2`,
        $button <: ensure_import_from($source),
}
```

**Comment by miridih-bgyu** [comment]
@morgante Thank you so much. 

Is there any place that I can see pure patterns?
e.g. imported_from(), remove_import(), jsx_element() .... 

This [site](https://docs.grit.io/patterns#linters) is just showing abstracted usage.

**Comment by morgante** [comment]
We need to improve documentation for our utility patterns. For now the best resource is probably just looking at the code itself: https://github.com/getgrit/stdlib/blob/bc2aad90806268020ba5d610cc2092abbf4e0484/.grit/patterns/js/imports.grit#L15
