### ISSUE TITLE
[Question] It's possible to automate "@jest/globals" import in test files

### ISSUE THREAD

**Issue by douglasjunior** [getgrit/gritql#28]
## Context

Since version 27, jest start to switch from using `@types/jest` where types are globally injected, like `jest`, `expect` and others modules, to manually import from `@jest/globals`.

So, we need to refactor all our tests files and import manually, like this:

```js
 import { jest, expect, describe, it, /* and others */ } from '@jest/globals';`
```

## Question

The challenge is: Find on all `*.spec.ts(x)` files, what modules were used (jest, expect, etc.) and then add a `import {...} from '@jest/globals'` for them.

It's possible with `gritql` to automate this refactoring?

**Comment by morgante** [comment]
Yes you can do this with GritQL:

```
engine marzano(0.1)
language js

or {`describe`, `expect`, `jest`, `it` } as $jest where {
    // Only in spec files
    $filename <: includes "spec",
    // Do the import
    $jest <: ensure_import_from(`"jest/globals"`)
}
```

Here's an example: https://app.grit.io/studio?key=KLvwe2Yq7ZQxc1U5P5CG6

**Comment by douglasjunior** [comment]
This is so nice!

Thank you @morgante and all the @getgrit contributors for this awesome tool!
