### ISSUE TITLE
The `https://grit.io/studio` site is stuck in an infinite loading loop.

### ISSUE THREAD

**Issue by gaki2** [getgrit/gritql#299]
<img width="937" alt="스크린샷 2024-05-02 오전 11 35 34" src="https://github.com/getgrit/gritql/assets/132441833/7e20f5bb-3047-4a0c-ae90-424c4579e8fd">

<img width="646" alt="스크린샷 2024-05-02 오전 11 38 15" src="https://github.com/getgrit/gritql/assets/76833478/979ad2fa-9403-40f7-a366-750f4387e853">

**Comment by morgante** [comment]
Do you have an ad blocker of some sort? You should try clearing your cache, I'm unable to reproduce this.

**Comment by gaki2** [comment]
I tried clearing the cache and using an incognito tab, but it's still not working. Have you tried clearing your cache? The reason you might not be able to reproduce the bug could be because you are using cached data.

**Comment by gaki2** [comment]
(I used it 4 days ago.)

**Comment by morgante** [comment]
Yes I cleared my cache and it's still working. Could you record in https://jam.dev/ and share that?

**Comment by gaki2** [comment]
https://jam.dev/c/fb5044aa-9040-446f-a0cd-b71f136a184b

**Comment by morgante** [comment]
Thanks! It looks like something is amiss with fetching Monaco from the CDN.

Can you try loading https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs/loader.js directly and see if there are any errors?

**Comment by gaki2** [comment]
It seems to be ok.
https://jam.dev/c/153d58f5-efc6-4a72-bf49-d9f6efa3b0ab

**Comment by morgante** [comment]
Hmm, maybe you can try a different browser then? From your error logs it's definitely having trouble loading Monaco.

**Comment by gaki2** [comment]
I've tried in Safari. But It still not work. 
When I use VPN (South Korea -> US), It works !!

**Comment by gaki2** [comment]
It works with no VPN.

**Comment by morgante** [comment]
Strange, but glad you got it working now.
