### ISSUE TITLE
Rewrite wrongly changes JavaScript `for` loop conditions

### ISSUE THREAD

**Issue by Sec-ant** [getgrit/gritql#307]
#### Pattern

```grit
engine marzano(0.1)
language js

`$body` => `$body`
```

#### Code before

```javascript
let i = 0;
for (; i < 10; ++i) {
  console.log(i);
}
```

#### Code After

```javascript
let i = 0;
for ( i < 10; ++i) {
  console.log(i);
}
```

#### Expected Behavior

The code shouldn't be modified. The first semicolon in the `for` loop should be preserved.

#### Reproduction

https://app.grit.io/studio?key=BOMSD-cdiDKk_eD23sSAg

**Comment by morgante** [comment]
This is likely a bug in our logic for cleaning up / removing empty statements that were deleted: https://github.com/getgrit/gritql/blob/662b6acd48acbe2190377458bc4dd1933543dc8d/crates/language/src/js_like.rs#L157
