### ISSUE TITLE
How to work with strings

### ISSUE THREAD

**Issue by jsardev** [getgrit/gritql#376]
I have a case where I need to migrate Tailwind CSS classes from scale values to `rem` values, e.g. `mt-4` should be `mt-[1rem]`.

I'm having trouble tinkering with GritQL in the Studio – I am able to get the `string_fragment` where the class is, but I don't know how to create a pattern that gets a part of a `string_fragment`.

Example:
```tsx
const Component = () => {
  return <div className="mt-4 gap-2 text-sm lg:mt-4 xxl:h-10">Test</div>
}
```

Now, using something like just `mt-4` does not work. I tried to do something like the following:

```
`className="$class"` where {
    $class <: "mt-4" => `mt-[1rem]`
}
```

But it doesn't work as well. How do I match specific items from the `className` for further rewrite? 🤔

**Comment by morgante** [comment]
We don't have great native string support today, so it's probably easiest to fall back to a JS function:

```
engine marzano(0.1)
language js

function remify($class) js {
    return $class.text.replaceAll("mt-4", "mt-[1rem]")
}

jsx_attribute(name=`className`, $value) where {
    $value => remify($value)
}
```

**Comment by jsardev** [comment]
Yeah that's what I ended up with and made it work. Thank you @morgante 🙌
