### ISSUE TITLE
`ensure_import_from` is raising error when used with `multifile`

### ISSUE THREAD

**Issue by edenhaus** [getgrit/gritql#393]
The following error is raised when `ensure_import_from` is used with `multifile`:
`Error Variable $GLOBAL_NEW_FROM_IMPORT_SOURCES is not bound`

The following example raised the error:
```grit
engine marzano(0.1)
language python

multifile {
    file () where {
        $import = "prod",
        $import <: ensure_import_from(source = `math`),
    }
}
```
https://app.grit.io/studio?key=AvtOwtL8zpgxq1GSVa0Wa&preset=_test_ensure_import_from

**Comment by morgante** [comment]
Yeah multifile patterns are a bit wonky / they require you to explicitly manage state.

What's your use case for multifile? We're probably going to deprecate it in the future given the complexity.

**Comment by edenhaus** [comment]
I'm trying to automatically migrate a Home Assistant integration to a new code style pattern by checking if the `__init__.py` file has a certain code. See https://github.com/home-assistant/core/blob/edenhaus-gritql/.grit/patterns/runtime_data_migration.md

The code should do something similar as in https://github.com/home-assistant/core/pull/120675

I also tried a way without `multifile`, but that will not work as the `__init__.py` file is checked as last in each directory, and I would require it to be evaluated first.


<details>
<summary>Non working rule without multifile</summary>


```grit
engine marzano(0.1)
language python

pattern refactor_functions($config_entry_type, $domain) {
    function_definition($name, $parameters, $body) as $func where {
        // change entry type
        $entry = $parameters[1],
        $entry <: typed_parameter(name=$entry_name, $type) where {
            $type <: type(type="ConfigEntry"),
        },

        if (and {$filename <: includes `__init__.py`, $name <: "async_setup_entry"}) {
            // migrate hass.data to entry.runtime_data
            $body <: contains assignment(left=$runtime_data) where {
                    $runtime_data <: or {
                        `hass.data.setdefault($...)[entry.entry_id]`,
                        `hass.data[$_][entry.entry_id]`,
                    },
                    $runtime_data => `$entry_name.runtime_data`
                },

            $config_entry_type_definition = `# TODO: Please add the correct type\n`,
            $config_entry_type_definition += `type $config_entry_type = ConfigEntry`,
            $func => `$config_entry_type_definition\n\n$func`,
            if ($GLOBAL_MODIFIED_DOMAIN <: undefined) {
                $GLOBAL_MODIFIED_DOMAIN = []
            },
            $GLOBAL_MODIFIED_DOMAIN += $domain
        },

        if ($GLOBAL_MODIFIED_DOMAIN <: includes $domain){
            // migrate hass.data to entry.runtime_data
            $body <: maybe contains assignment($left, right=$runtime_data) as $assigment where {
                $runtime_data <: `hass.data[$_][entry.entry_id]`,
                $assigment => `$left = $entry_name.runtime_data`
            },

            if ($filename <: not includes `__init__.py`) {
                $config_entry_type <: ensure_import_from(source = `.`),
            },
            $type => $config_entry_type
        },
    }
}

file($name, $body) where {
    $file_parts = split($name, "/"),
    $components_folder = $file_parts[-3],
    //$components_folder <: includes `components`, // with includes we allow also custom_components
    $domain = $file_parts[-2],
    $config_entry_type = capitalize($domain),
    $config_entry_type += "ConfigEntry",
    $body <: contains refactor_functions($config_entry_type, $domain)
}
```

</details>

I'm new to gritql and probably the pattern can be optimized :)

**Comment by morgante** [comment]
Got it, yeah if you are trying to work across multiple files then multifile is currently your best option until I release a JS/Python SDK.

The way we do imports you need to manually create the "state" for each file by wrapping like so:

```
multifile {
    file() as $file where {
        $file <: before_each_file(),
        $import = "prod",
        $import <: ensure_import_from(source = `math`),
        $file <: after_each_file()
    }
}
```

**Comment by edenhaus** [comment]
Thanks for the help :)
Is the a difference between running the grit rule in studio (https://app.grit.io/studio?key=A_pBfHO-XuQyFvitrJf9a) or using the cli with `grit apply runtime_data_migration homeassistant/components/airvisual`?
The imports work in the studio but not with the cli for the same rule.

When I comment out `$config_entry_type <: ensure_import_from(source = `.`),` the other files (ex. `senor.py`) get modified, when imported only the `__init__.py` get modified.

I installed the cli with
```zsh
ha-venv@edenhaus ➜ /workspaces/core (edenhaus-gritql) $ curl -fsSL https://docs.grit.io/install | bash                      
downloading marzano 0.1.0-alpha.1719826984 x86_64-unknown-linux-gnu
installing to /home/vscode/.grit/bin
  marzano
everything's installed!
```

**Comment by morgante** [comment]
The order of multifile is not guaranteed, and by default all variables share global state. If you want to scope things to a specific file you should use bubble:

```
engine marzano(0.1)
language python

multifile {
    bubble file() where {
        $import = "prod",
        $import <: ensure_import_from(source = `math`),
    }
}
```

**Comment by edenhaus** [comment]
It did not work for me, so I wrote a custom import pattern

```grit
pattern import_from_custom($source) {
    $name where {
        $program <: module($statements),
        $statements <: contains or {
                import_from_statement(),
                import_statement(),
            } as $import,
        // Ruff will handle double imports and sorting for us
        // So we add always the import
        $import => `from $source import $name\n$import`,
    }
}
```

Thanks anyways @morgante
