### ISSUE TITLE
Request to change `anyhow` to `thiserror` (or custom error) in `grit-pattern-matcher`

### ISSUE THREAD

**Issue by ematipico** [getgrit/gritql#409]
Mostly because `anyhow` is meant for [application code](https://github.com/dtolnay/anyhow?tab=readme-ov-file#comparison-to-thiserror), and this forces downstream dependencies (Biome for example) to use `anyhow` to import the types and correctly handle the errors.

I wonder if you're open to changing this for a custom error or us the library `thiserror`. I am happy to send a PR too.

**Comment by morgante** [comment]
This has been on the back of my mind for a while, so definitely happy to change and would certainly appreciate a PR to move the core library crates over to thiserror.
