### ISSUE TITLE
Hanging commas after removing kwargs in Python

### ISSUE THREAD

**Issue by MartinBernstorff** [getgrit/gritql#416]
Continuing from Discord [message](https://discord.com/channels/1140989670751219762/1140989757392953424/1261006232618143877).

```grit
`TaskMetadata($args)` where {
    $args <: any {
        contains `n_samples=$_` as $ns_kwarg where {
            $ns_kwarg <: `n_samples = $ns_val` => .
        },
        contains keyword_argument(name="avg_character_length") as $avg_kwarg where {
            $avg_kwarg <: `avg_character_length = $avg_val` => `stats=GeneralDescriptiveStats(n_samples=$ns_val, avg_character_length=$avg_val)`
        },
    },
}
```

```python
from pydantic import BaseModel


class TaskMetadata(BaseModel):
    n_samples: dict[str, int]
    avg_character_length: dict[str, float]


if __name__ == "__main__":
    TaskMetadata(
        name="TbilisiCityHallBitextMining",
        dataset={
            "path": "jupyterjazz/tbilisi-city-hall-titles",
            "revision": "798bb599140565cca2dab8473035fa167e5ee602",
        },
        description="Parallel news titles from the Tbilisi City Hall website (https://tbilisi.gov.ge/).",
        type="BitextMining",
        category="s2s",
        eval_splits=[_EVAL_SPLIT],
        eval_langs=_EVAL_LANGS,
        main_score="f1",
        domains=["News"],
        text_creation="created",
        n_samples={_EVAL_SPLIT: 1820},
        reference="https://huggingface.co/datasets/jupyterjazz/tbilisi-city-hall-titles",
        date=("2024-05-02", "2024-05-03"),
        form=["written"],
        task_subtypes=[],
        license="Not specified",
        socioeconomic_status="mixed",
        annotations_creators="derived",
        dialect=[],
        bibtex_citation="",
        avg_character_length={_EVAL_SPLIT: 78},
    )
```

Morgante suggested it might be a bug somewhere around [here](https://github.com/getgrit/gritql/blob/9587e9e5558c583d69514c1f581f8244ac551616/crates/core/src/inline_snippets.rs#L298).

Results in a dangling comma:
![image copy](https://github.com/getgrit/gritql/assets/8526086/c7cd828f-90e4-4750-bdaa-94884605374b)

**Comment by MartinBernstorff** [comment]
Thanks a ton for the work you do! The DSL is super interesting, and love it being open source.

**Comment by morgante** [comment]
> Thanks a ton for the work you do! The DSL is super interesting, albeit/because it is a challenge to wrap my head around. Love it being open source!

Thank you! Please also do provide feedback on areas we could improve the documentation for.

For this issue, the fix will involve our comma [algorithm](https://github.com/getgrit/gritql/blob/9587e9e5558c583d69514c1f581f8244ac551616/crates/core/src/inline_snippets.rs#L298). Happy to accept a PR if someone fixes this case.
