### ISSUE TITLE
clearer messages when a referenced file is missing

### ISSUE THREAD

**Issue by jacobbednarz** [getgrit/gritql#423]
Earlier today, I was updating some patterns and when I went to run `grit patterns test` hit the following.

```
$ grit patterns test
Error: No such file or directory (os error 2)
```

I did all the usual things thinking this was something I broke in my environment (somehow lost grit) however, that all looked good. After a while, I busted out strace and it turned out this came from grit trying to look up a file in the pattern.

```
$ strace -f -e trace=open,openat ~/.grit/bin/grit patterns test

.. snip

[pid   799] openat(AT_FDCWD, "/mnt/share/.grit/grit.yaml", O_RDONLY|O_CLOEXEC) = 9
[pid   799] openat(AT_FDCWD, "/mnt/share/.grit/../docs/guides/version_5_upgrade.m", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   798] +++ exited with 0 +++
[pid   797] +++ exited with 0 +++
[pid   791] +++ exited with 0 +++
[pid   799] +++ exited with 0 +++
Error: No such file or directory (os error [pid   799] openat(AT_FDCWD, "/mnt/share/.grit/../docs/guides/version_5_upgrade.m", O_RDONLY) = -1 ENOENT (No such file or directory)
2)

.. snip
```

Yep, I did a stupid and removed a trailing letter of the file extension.

To make this easier to debug for others, perhaps wrapping this sort of error up in a nicer handler would be useful? Something like this would be helpful: 

```
$ grit patterns test

Failed to find pattern at "/mnt/share/.grit/../docs/guides/version_5_upgrade.m". Does it exist?
```

**Comment by asr2003** [comment]
/attempt #423 
@morgante Will add error handling in `analyse.rs` file to handle the issue of missing file references and to enhance the error handling within the `walk_call_tree` and `find_child_tree_definition` functions

**Comment by morgante** [comment]
Thanks @asr2003, please be sure to include an integration test in https://github.com/getgrit/gritql/tree/main/crates/cli_bin/tests

**Comment by asr2003** [comment]
@morgante I have seen two related files of it.
crates\cli\src\commands\patterns.rs
crates\core\src\analysis.rs

Do I make changes to both files or patterns.rs is fine?

**Comment by morgante** [comment]
You need to solve the issue. I'm not going to handhold you through every detail.

**Comment by ORESoftware** [comment]
my first stab at it: https://github.com/getgrit/gritql/pull/479
