### ISSUE TITLE
C# Support

### ISSUE THREAD

**Issue by NonlinearFruit** [getgrit/gritql#438]
Supporting C# as a language for matching against would great! There is a lot of language tech debt hanging around from things like:
- .Net Framework to .Net Core to .Net
- Major release versions every year

Microsoft hasn't provided any official migration paths so a tool like gritql would be super useful.

Review [this guide](https://github.com/getgrit/gritql/blob/main/CONTRIBUTING.md#adding-a-new-target-language) and join us on Discord to discuss.

## Acceptance criteria
1. Working grammar + language support
2. At least 10 test cases, including rewrites and metavariables.

**Comment by morgante** [comment]
C# support is definitely interesting for us and planned for this fall.

**Comment by GTB3NW** [comment]
really keen to see c# support. Some competing tools in the same do support it already but gritql looks like the better tool for robust AST s&r - looking forward to seeing this land!

**Comment by urbit-pilled** [comment]
I'm interested in finishing this task (but only if @onyedikachi-david is no longer interested)

**Comment by morgante** [comment]
@onyedikachi-david Can you confirm if you plan to continue?

**Comment by onyedikachi-david** [comment]
Yes I am, i got distracted with other jobs. I'll be wrapping it up soon.

**Comment by urbit-pilled** [comment]
It's been a while since the last signs of progress, so I think it's fair that I jump in and complete this bounty.
/attempt #438

**Comment by morgante** [comment]
Thanks @urbit-pilled this looks good.

**Comment by morgante** [comment]
Algora is broken so I need to aware this manually.

/tip @urbit-pilled $250
