### ISSUE TITLE
Aliases for `--lang`

### ISSUE THREAD

**Issue by morgante** [getgrit/gritql#445]
I'd like to be able to use aliases like `py` for the lang argument:

```
grit apply --lang py 'identifier()'
error: invalid value 'py' for '--language <LANGUAGE>'
  [possible values: js, html, css, json, java, csharp, python, markdown, go, rust, ruby, solidity, hcl, yaml, sql, vue, toml, php, phponly]

  tip: a similar value exists: 'python'
```

**Comment by ORESoftware** [comment]
looking at this - I don't see '--language' or 'invalid value' in the codebase - looking for the source for the CLI option `grit apply`

**Comment by morgante** [comment]
@itsdheerajdp Don't submit code you never ran. Until you actually validate that the command shared fixes the issue it isn't worth my time to review.
