### ISSUE TITLE
grit-cli apply usability with patterns provided inline

### ISSUE THREAD

**Issue by eyurtsev** [getgrit/gritql#452]
At the moment, it's inconvenient to use grit apply / check with patterns provided inline.

If the syntax were a bit more convenient, i'd probably replace my usage of `grep`  for basic searches

For example, I'm trying to find occurrences of `__fields__`? Should I use `apply` or `check`?

```python
grit apply  ``'`__fields__`'``
```

**Comment by morgante** [comment]
You should use `apply`. `grit check` is for linting/checking patterns you have enforced in your `.grit` directory.

Note that you need to specify the language. This is what you're looking for:

```
grit apply --lang python '`__fields__`'
```
