### ISSUE TITLE
PHP language support

### ISSUE THREAD

**Issue by morgante** [getgrit/gritql#48]
We would like to support PHP as a language for matching against.

Review [this guide](https://github.com/getgrit/gritql/blob/c8f9160197e68aa5340a45f19005706a13a60f30/CONTRIBUTING.md#adding-a-new-target-language) and join us on Discord to discuss.

## Acceptance criteria
1. Working grammar + language support
2. At least 10 test cases, including rewrites and metavariables.

**Comment by morgante** [comment]
@iamnamananand996 Do you want to attempt this bounty?

**Comment by abhishek818** [comment]
@morgante can I get assigned?

**Comment by urbit-pilled** [comment]
/attempt #48  
I've made a few tools using tree-sittter (https://github.com/urbit-pilled/tree-sitter-hoon and https://github.com/urbit-pilled/hoon-ts-editors) so I'd like to work on this

**Comment by iamnamananand996** [comment]
> @iamnamananand996 Do you want to attempt this bounty?

hi @morgante, yes I am on it, look like a race now, 😃, let see who wins.

**Comment by morgante** [comment]
@abhishek818 @urbit-pilled @iamnamananand996 I will assign this bounty to someone once they land the first main PR (ex. adding the grammar + parse test + initial metavariables).

**Comment by ayewo** [comment]
@morgante 

The [`tree-sitter-php`](https://github.com/tree-sitter/tree-sitter-php) project adopted the same split as `tree-sitter-typescript` two months ago[^1] where they have two dialects: `php_only` and `php`.
* `php_only`: which allows top level statements, start/end tags are optional;
* `php`: which parses both PHP and HTML (i.e. normal PHP parser since PHP started out as a templating language).

1. Which of these two grammars should we pick for the initial support? I imagine this will be `php_only`?
2. How do we approach naming of the two dialects within the Grit project? Naming is hard and agree that in an ideal world[^2] it would have been better to use the names: 
   * `php_only` => `php` 
   * `php` => `php_html`



[^1]: https://github.com/tree-sitter/tree-sitter-php/pull/192
[^2]: https://github.com/tree-sitter/tree-sitter-php/pull/180#issuecomment-1774160626

**Comment by morgante** [comment]
Hi @ayewo, thanks for flagging this.

I think we probably want to use `php` as the default, since that matches the largest number of PHP codebases in the wild.

For toggling between them, we should use the `flavor` mechanism we added for JS/TS [here](https://github.com/getgrit/gritql/blob/61241d62777664d4487437c41555af40ffb6e42b/crates/language/src/target_language.rs#L164). This would support `language php(html)` or `language php(only)` with the default as `php(only)`.

**Comment by urbit-pilled** [comment]
Finally got metavariables to work in my PR, this commit contains the biggest changes I had to make: :https://github.com/getgrit/gritql/pull/52/commits/197575d534326e8913b5f788780d3ab181d5cfce

**Comment by digital-phoenix** [comment]
@morgante I just submitted a pull request that solves this issue why are you assigning this to someone else?

**Comment by morgante** [comment]
@digital-phoenix I'm sorry you went into the effort of submitting a pull request, but we can only award the bounty to one person. @urbit-pilled's PR is earlier and closer to completion.

**Comment by digital-phoenix** [comment]
@urbit-pilled  test cases are not even generating abstract syntax trees yet it is just doing regex comparisons. In order for php to see text as code it has to be contained within php tags. My test cases work not just as regex comparisons but as actual code.

**Comment by morgante** [comment]
I don't think `<?php` is required when using the php-only grammar.

**Comment by digital-phoenix** [comment]
@morgante I tested it before when I was adding php. Unless you use <?php the test will just be interpreted as text. Just using regex leads to issues such as not being able to match a function body when it is split across multiple lines.

**Comment by morgante** [comment]
Language support is usually not completed in a single PR. I plan to merge @urbit-pilled's PR and award part of the bounty, but will award additional bounties for PRs adding more test cases and fixing associated bugs.

**Comment by digital-phoenix** [comment]
@morgante @urbit-pilled's grammar file does not seem to even compile correctly. It seems to contain conflicts that have not been included in the conflict table I'm not convinced they have ever even used their own grammar file. Whereas my code includes support for a broad range of language features.

**Comment by morgante** [comment]
If the grammar file wasn't used I don't see how the test cases could pass.

**Comment by digital-phoenix** [comment]
@morgante I understand the importance of collaboration but your'e backing code that doesn't work properly over everyone else's efforts

**Comment by morgante** [comment]
> @morgante I understand the importance of collaboration but you're backing code that doesn't work properly over everyone else's efforts

90% of the work is the same in your PRs. It would not be fair to discard the earlier PR, even if it is incomplete.

As I noted, you will have an opportunity to add (and fix) more test cases for your share.

For what it's worth, this is making me see the problems with the bounty model. We put this out as an experiment, but it's becoming a lot of trouble to manage.

**Comment by ayewo** [comment]
> For what it's worth, this is making me see the problems with the bounty model. We put this out as an experiment, but it's becoming a lot of trouble to manage.

I was trying to point this out this very scenario playing out in Discord. Glad you've also come to the same conclusion—it can cause some bad blood for contributors and logistical headaches for projects that is completely avoidable. 

As I said, battle royale style, only works well if the bounty is a few hours of work. This is a multi-day PR.

**Comment by digital-phoenix** [comment]
@morgante if you are going to have a public bounty either you need to accept whoever provides the first work that solves the requirements or you need to assign the task to someone. 

Most of the code will be the same because this project requires a lot of boiler plate to add a language. But the most important part the changes to the base grammar files are different.

**Comment by digital-phoenix** [comment]
@ayewo battle royale style is a lot riskier but I think it can work okay as long as the submissions are easy to measure and are all compared against a well defined benchmark.

**Comment by morgante** [comment]
As far as I know, I am not required to accept any pull request. If you prefer not to contribute to our repository, I understand, but I'm just trying to be fair to everyone.

**Comment by digital-phoenix** [comment]
@morgante if you base this off of whoever opens a PR first that just encourages people to open broken buggy PRs. Which will just make work for you.

**Comment by urbit-pilled** [comment]
> @morgante @urbit-pilled's grammar file does not seem to even compile correctly. It seems to contain conflicts that have not been included in the conflict table I'm not convinced they have ever even used their own grammar file. Whereas my code includes support for a broad range of language features.

> @morgante @urbit-pilled's test cases are not even generating abstract syntax trees yet it is just doing regex comparisons. In order for php to see text as code it has to be contained within php tags. My test cases work not just as regex comparisons but as actual code.

You may have been testing an older version?, Because the grammar file does compile correctly.And the test cases are not regex matches, and the php tags are optional if you set php_only as the default which was requested earlier in the comment thread.

I think you started too late @digital-phoenix , because your PR doesn't implement the prefix change (^ instead of $) or support php without tags yet. I already finished what you did in the first day (get php working without prefix change) on my PR but you have added more tests.

**Comment by morgante** [comment]
Thanks @urbit-pilled for landing the main PR here. I'll award $1k from the bounty for that. There's still a bit more work to be done to consider this complete:
- PHP templates (ie. in HTML) should be supported as an alternative flavor (like we have in JS) with `language php(html)`
- We definitely need more test coverage, I'd like at least 5-6 more cases.

**Comment by ayewo** [comment]
> I'll award $1k from the bounty for that. 

@morgante Algora has a command for making partial awards on GitHub. Simply add a comment on this issue with:
`/tip $1000 @urbit-pilled`

Apologies if you already know this.

**Comment by urbit-pilled** [comment]
Thanks morgante, I'll work on the rest today.

**Comment by morgante** [comment]
Tests cases that should work:

- `echo $_`

**Comment by urbit-pilled** [comment]
hey @morgante you need to click on the link posted by algora-pbc to award the tip. it hasn't been awarded yet.

> 👉 @morgante: [Navigate to your dashboard to proceed](https://console.algora.io/org/grit/bounties?status=open)

**Comment by urbit-pilled** [comment]
> Tests cases that should work:
> 
> * `echo $_`


just added a test case for this called `php_echo`
```
`echo ^_;` => `print "modified;`
```
The prefix in php is `^` instead of `$` and there is a semicolon needed due to: https://github.com/getgrit/gritql/pull/52#discussion_r1541360156

**Comment by urbit-pilled** [comment]
@algora-pbc what are the correct commands to use when paying out a bounty incrementally?

**Comment by urbit-pilled** [comment]
Anything else that needs to be done for the rest of this bounty @morgante? (currently $1250 paid from $1500 bounty)

**Comment by morgante** [comment]
Hi @urbit-pilled, before we consider a language "complete" we usually like to try it on a few repos and run some sample migrations. For this to be complete, I think I'd like to see:

- Run this on some larger open source codebases and make sure you don't see tons of parse errors
- Add 1-2 sample rules to the PHP stdlib: https://github.com/getgrit/stdlib/tree/main/.grit/patterns

**Comment by varshith257** [comment]
@morgante Anything left with this to complete the issue further. From conversations I have seen there is some part of bounty to add test cases more and increase test coverage.

Would I proceed with it ?

**Comment by morgante** [comment]
@varshith257 We haven't seen much PHP usage so I'm closing this out. No further bounty is available.
