### ISSUE TITLE
Watch mode for `grit patterns test`

### ISSUE THREAD

**Issue by morgante** [getgrit/gritql#51]
We would like to have a watch mode for `grit patterns test --watch`.

Watch mode should be similar to other testing/CLI tools that offer a watch mode: when files change, re-run tests.

## Acceptance criteria
- Watch mode should watch for file changes to any patterns in the `.grit` directory and automatically re-run those tests
- If a file changes, only the *affected* patterns should be re-run. Ex. if I edit [this file](https://github.com/getgrit/stdlib/blob/main/.grit/patterns/js/add_playwright_tags.md) then only that pattern test should re-run.
- You will also need to account for pattern dependencies. Ex. if https://github.com/getgrit/stdlib/blob/main/.grit/patterns/js/imports.grit is edited then any patterns which use the `ensure_import_from` pattern should be re-run. Utilities like [this](https://github.com/getgrit/gritql/blob/c8f9160197e68aa5340a45f19005706a13a60f30/crates/core/src/pattern/compiler.rs#L563) can be leveraged for walking the call graph
- At least 2 tests should be included, including ideally at least one integration test of the final binary like we do [here](https://github.com/getgrit/gritql/tree/main/crates/cli_bin/tests).

**Comment by webbdays** [comment]
@el-buku 
any progress.
still on this?

**Comment by el-buku** [comment]
For sure, started earlier I’ll open a draft PR

**Comment by vivasvan1** [comment]
@Sambit003 @el-buku 
Hi there fellas,

Are you working on this? 
If yes, let me know if you interested in working togather.
If no, I would like to attempt it.

Hope u have a nice day.

**Comment by varshith257** [comment]
@morgante Is this issue open to grab? 
Have some good approach in my mind

**Comment by morgante** [comment]
@varshith257 No, this is already complete and I will award the bounty to @Ashu999. Feel free to open a PR with an improved approach if you have one in mind.

**Comment by varshith257** [comment]
@morgante It seems already PR is merged. How my work reflects it and rewarded?

**Comment by morgante** [comment]
@varshith257 You did no work for that PR. Why would you be rewarded for something you made no contributions to?

**Comment by varshith257** [comment]
@morgante I think we misunderstood. You said to open a PR with my approach. So that's I am asking for 😅

**Comment by morgante** [comment]
@varshith257 This is an open source repository, under a permissive license. If you have a superior approach, provide a PR. We will not be paying for every PR.

If you expect every single PR on every repo will be "compensated" you do not understand the ethos of open source.

**Comment by varshith257** [comment]
Hey @morgante I got you.There are some orgs bountied for multiple PRs as one the case here. So thought in that way. Ok, I will check @Ashu999 implementation and will propose my improvements 😄

**Comment by varshith257** [comment]
PS: I have contributed to different organisations as OS Contributer. But it's now time to upgrade my old Windows 10 PC. So searching some cool bounties which I can get with them and buy it by my birthday on July 25(makes me some confident of reaching my target too)

**Comment by morgante** [comment]
Thanks @varshith257, I appreciate your understanding. I'm also happy to awards tips for good contributions and will consider opening more bounties in the future.
