### ISSUE TITLE
marzano name is confusing

### ISSUE THREAD

**Issue by tmcw** [getgrit/gritql#519]
I went to try and upgrade grit on my computer and ran the install command from the docs: https://github.com/getgrit/gritql?tab=readme-ov-file#getting-started

```
curl -fsSL https://docs.grit.io/install | bash
```

That reports

```
downloading marzano 0.1.0-alpha.1726760684 aarch64-apple-darwin
installing to /Users/tmcw/.grit/bin
  marzano
everything's installed!
```

A bit confusing - `marzano`? The docs mention using `grit`, not `marzano`. It's a little sketchy on first glance because the whole "running an arbitrary curl'ed script to install something" already is skating close to bad security practices, seeing install messages about a different thing than what I expected to install was a bit scary.

**Comment by morgante** [comment]
This is from the legacy where we originally had a different (Node) CLI that was talking to the "Marzano" Rust binary, but I agree it's confusing at this point and we should just do the work to consolidate.

Note you should still have an alias for `grit` automatically added into the bin as well.

**Comment by tino** [comment]
About that "marzano", some examples contain `engine marzano(0.1)` as the first line. Is that necessary? Does it change anything?

**Comment by morgante** [comment]
> About that "marzano", some examples contain `engine marzano(0.1)` as the first line. Is that necessary? Does it change anything?

It doesn't currently change anything, but does indicate the version the pattern was written against. In the future, if we make breaking changes, we might use this to preserve backwards compatibility.
