### ISSUE TITLE
Read-only filesystem error

### ISSUE THREAD

**Issue by musjj** [getgrit/gritql#535]
I'm trying to run gritql on NixOS, but I'm getting this error:

```bash
$ grit apply ...
Error: Read-only file system (os error 30)
```

Of course, I'm not currently in a read-only filesystem, but in my normal project directory.

Is gritql trying to modify files in the installation directory here? If so, this means that gritql currently cannot be packaged in most Linux distributions.

**Comment by morgante** [comment]
Can you try running grit init first?

Please share the output of grit doctor.

**Comment by musjj** [comment]
Both of the commands returns the same error unfortunately:

```bash
$ grit doctor
Error: Read-only file system (os error 30)

$ grit init
Error: Read-only file system (os error 30)
```

But `--help` works:

```bash
$ grit --help
Software maintenance on autopilot, from grit.io
...
```

**Comment by morgante** [comment]
This will be fixed in the next release. Note you will need to run `grit init` to initialize a local (writable) dir to store gritmodules which we download from GitHub.

**Comment by collinc777** [comment]
I'm getting this error when trying run the gritql in the `Grit: Search with GritQL` window

**Comment by morgante** [comment]
@collinc777 Can you try running `grit doctor` and `grit apply "something"` from the CLI?

**Comment by collinc777** [comment]
```bash
grit doctor
```
```bash
Client environment
  OS: macos
  Architecture: aarch64
  Build SHA: 20f89f066662e963333cdf3f01eae731f7fda06f
Configuration
  Expected location: /opt/homebrew/lib/node_modules/@getgrit/cli/node_modules/manifests.json
  Config: local config at /Users/collincaram/projects/scadmin/.grit
  Existing Grit modules dir: /Users/collincaram/projects/scadmin/.grit/.gritmodules
  Grit API URL: https://api2.grit.io (override by setting GRIT_API_URL)
  Grit GraphQL API URL: https://grit-prod-central.hasura.app/v1 (override by setting GRAPHQL_API_URL)
  Grit App URL: https://app.grit.io (override by setting GRIT_APP_URL)
Authentication
  You are not authenticated.
Installed binaries
  gouda: not installed. Run grit install to install missing binaries
  workflow-runner: not installed. Run grit install to install missing binaries```
  
  ```bash
  grit apply hello_world
  ```
  ```
  Processed 2499 files and found 0 matches
  ```
  (The 0 matches is expected)

**Comment by collinc777** [comment]
should I open another ticket?

**Comment by morgante** [comment]
Sure.
