### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by morgante** [getgrit/gritql#56]
We would like to support Ruby as a language for matching against.

Review [this guide](https://github.com/getgrit/gritql/blob/main/CONTRIBUTING.md#adding-a-new-target-language) and join us on Discord to discuss.

## Acceptance criteria
1. Working grammar + language support
2. At least 10 test cases, including rewrites and metavariables.

## Assignment approach
Since this is a large project, here is how we will tackle it:
- If anyone who has already successfully contributed a grammar wants to take it on, we will assign them first dibs.
- Others are welcome to contribute. We will assign the bounty to the first *major* PR submitted that is close to complete.

## Votes
- 3

**Comment by oliverqx** [comment]
can i get assigned? 

cc: @morgante

**Comment by morgante** [comment]
You are welcome to contribute. I won't assign it to one person until I have seen a meaningful PR.

**Comment by urbit-pilled** [comment]
/attempt #56
the tree-sitter-ruby repo currently has a problem with building a valid wasm file, but this is fixable.
