### ISSUE TITLE
openai migrate error Failed to download Gritcli from

### ISSUE THREAD

**Issue by olebrussels** [getgrit/gritql#576]
hello team, i am having an issue and i need your help because i dont find any solution to this problem. 
I am trying to use  openai.ChatCompletion.create( to call openai api. but this is no longer supported in openai>1.0

I did pip install --upgrade openai and openai migrate in my python venv installed on an ubuntu 20.04
but i get an error message when running my "openai migrate"

`Downloading Grit CLI from https://github.com/getgrit/gritql/releases/latest/download/marzano-x86_64-unknown-linux-gnu.tar.gz
Error: Failed to download Grit CLI from https://github.com/getgrit/gritql/releases/latest/download/marzano-x86_64-unknown-linux-gnu.tar.gz
`

can somebody tell me a hint on how to solve this? thank you!

**Comment by morgante** [comment]
You can try installing the Grit CLI directly: https://docs.grit.io/cli/quickstart

Then just run `grit apply openai`.

**Comment by morgante** [comment]
Closing this since there's already an issue on the openai repo: https://github.com/openai/openai-python/issues/1838
