### ISSUE TITLE
Question: Dynamic description

### ISSUE THREAD

**Issue by Nikoms** [getgrit/gritql#592]
Hello!

I would like to use GritQL as a kind of "best practice/architecture test" tool for our company and I'm wondering if we can have dynamic description. For example, let's say that I would like to warn our engineers that  some libraries should not be used anymore. My idea was to have a warning for each file saying the library "XYZ" is deprecated. The idea would be to know which module is using which library without having to create  one rule per library for example. I would then parse the output in order to create a summary.

Is there a way to achieve this easily?

Thank you :)

**Comment by morgante** [comment]
You can include a description for patterns, but it's not dynamic: https://docs.grit.io/guides/authoring#example

If you are doing some post-processing anyways, I suggest using the `--json` or `--jsonl` formats, as they give you access the underlying matched text where you could extract specific code.
