### ISSUE TITLE
Re-indentation

### ISSUE THREAD

**Issue by jonathan-s** [getgrit/gritql#73]
I'm looking through the docs and wonder how to handle re-indentation. The use case would be to re-write a python `unitttest.TestCase` class to using `pytest` which is plain python functions.

**Comment by ilevyor** [comment]
For languages with semantic whitespace we calculate how much to reindent when doing the rewrite. you can follow the rewrite logic starting at text_unparser.rs

**Comment by morgante** [comment]
Grit should automatically handle removing the white-space if you structure your query to not use the class.

Example: https://app.grit.io/studio?key=jdcyl3I8UCOr1F_WxhQ-z

**Comment by jonathan-s** [comment]
Thank you so much for the example @morgante
