### ISSUE TITLE
`export default function $name() {}` doesn't match correctly

### ISSUE THREAD

**Issue by SimeonC** [getgrit/gritql#82]
See playground here: https://app.grit.io/studio?key=SagGy0msuq3fQLmcDXA8z

![CleanShot 2024-03-27 at 13 35 24](https://github.com/getgrit/gritql/assets/1085899/e2d8d9a9-61b9-4d1e-b334-878338d3beff)

As you can see trying to match a non-anonymous default export function is currently matching the same as `export function`.

**Comment by morgante** [comment]
Thanks for the report. We probably need to adjust the field for default.
