### ISSUE TITLE
Doesn't handle removal of trailing whitespace for python language

### ISSUE THREAD

**Issue by jonathan-s** [getgrit/gritql#84]
In the following example https://app.grit.io/studio?key=jdcyl3I8UCOr1F_WxhQ-z we have some valid python code that runs perfectly fine. But because the editor has been set to remove trailing whitespace grit complains that the code is not properly indented, when in fact this is valid python and runs fine as is.

**Comment by morgante** [comment]
We might just need to adjust this: https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IGlobalEditorOptions.html#trimAutoWhitespace

It's a problem in the studio (not GritQL) so the CLI should work fine.

**Comment by ilevyor** [comment]
@jonathan-s  Is the problem that the online editor at app.grit.io strips trailing whitespace, or that your personal editor strips the whitespace, I believe
https://github.com/getgrit/gritql/pull/99
should fix

**Comment by jonathan-s** [comment]
My personal editor strips whitespace
